name: Deploy-LIVE
on:
  push:
    branches:
      - test-main
  pull_request:
    branches:
      - test-main

jobs:
  build:
    runs-on: ubuntu-20.04 # 해당 github actions 스크립트가 작동할 OS 환경 지정
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # 프로젝트 코드 checkout

      - name: Check Node v # Node v 확인
        run: node -v

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2
        run: |
          aws s3 cp --recursive --region ap-northeast-2 dist s3://allini
