name: Deploy-LIVE
on:
  push:
    branches:
      - test-main
  pull_request:
    branches:
      - test-main

jobs:
  build:
    runs-on: ubuntu-20.04 # 해당 github actions 스크립트가 작동할 OS 환경 지정
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # 프로젝트 코드 checkout

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.18.2" # 워크플로우가 실행되는 환경에서 사용할 Node.js의 버전
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build

      # 현재 시간을 출력하고, 이를 GitHub Actions의 출력 변수에 저장하여 배포 시점 추적 및 버전 관리 수행
      - name: Current timestamp
        id: timestamp
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H-%M-%S-%3NZ')"

      - name: Deploy
        run: |
          aws s3 cp dist s3://allini
          aws cloudfront create-invalidation --distribution-id E2SSGMISK1VWI1 --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2
